/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptologyApp.controller;

import cryptologyApp.view.ConsoleView;

public class App {

  public static void main(String[] args) {
    ConsoleView view = new ConsoleView();
    MainController controller = new MainController(view);

    controller.start();
  }
}
