/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cryptologyApp;

import org.junit.jupiter.api.Test;

import cryptologyApp.controller.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    /*
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
